# Generated by Django 4.1.1 on 2022-09-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("region", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="country_name",
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
